version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    ports: 
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=semir
      - MONGO_INITDB_ROOT_PASSWORD=Semir.123
    volumes:
      - mongo-db:/data/db
  redis: 
    image: redis
volumes:
  mongo-db: